{% set name = "exceptiongroup" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/exceptiongroup-{{ version }}.tar.gz
  sha256: 47c2edf7c6738fafb49fd34290706d1a1a2f4d1c6df275526b62cbb4aa5393cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
    - flit-scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - exceptiongroup
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/exceptiongroup/
  summary: Backport of PEP 654 (exception groups)
  license: MIT and PSF-2.0
  license_file: LICENSE
  dev_url: https://github.com/agronholm/exceptiongroup
  doc_url: https://docs.python.org/3/library/exceptions.html

extra:
  recipe-maintainers:
    - xylar
